# Generated by Django 4.2.11 on 2024-03-12 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_dealership_api", "0002_brand_vehicle_brand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feature",
            name="price",
        ),
    ]
